#pragma config(Sensor, S2,     sensorSonar,         sensorSONAR)
#pragma config(Sensor, S3,     sensorRGB,      sensorColorNxtRED)
#pragma config(Sensor, S4,     sensorLight,    sensorLightActive)
#pragma config(Motor,  motorB,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma platform(NXT)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef enum {
	MOVING = 0,
	STOPPED = 1,
	RIP = 2
} State;

// GLOBALS
const int MAX_SPEED = 50;
const int VIEW_DIST = 25;
State STATE = STOPPED;
// Bluetooth gobals
const int kMaxSizeOfMessage = 30;
const int INBOX = 5;

// ---------
// FUNCTIONS
// ---------

/**
* @brief Checks for bluetooth messages and sets command string
* @param command String to hold the bluetooth message
*/
void checkBluetoothMessage(string &command) {
	int nSizeOfMessage;
	TFileIOResult nBTCmdRdErrorStatus;
	ubyte nRcvBuffer[kMaxSizeOfMessage];
  nSizeOfMessage = cCmdMessageGetSize(INBOX);

  if (nSizeOfMessage > kMaxSizeOfMessage)
    nSizeOfMessage = kMaxSizeOfMessage;

  if (nSizeOfMessage > 0){
  	nBTCmdRdErrorStatus = cCmdMessageRead(nRcvBuffer, nSizeOfMessage, INBOX);
  	nRcvBuffer[nSizeOfMessage] = '\0';
  	stringFromChars(command, (char *) nRcvBuffer);
  }
}

/**
* @brief Reduce motor speed of robot slowly
*/
void slowBreak() {
	int speed = ((motor[motorLeft] > motor[motorRight]) ? motor[motorLeft] : motor[motorRight]);
  for (int i = speed; i > 0; i--) {
    motor[motorLeft] = i;
    motor[motorRight] = i;
		displayBigTextLine(3, "s: %d", i);

    wait1Msec(10);
  }
  motor[motorLeft]  = 0;
  motor[motorRight] = 0;
}

/**
* @brief Plays sound
*/
void makeSound(){
	playSound(soundUpwardTones);
}

/**
* @brief Move state, moves robot etc
* Move state does the following:
* 	- Uses checkBluetoothMessage function to get command
*   - Sets robot state to STOPPED when "FIRE" command is given
*		- Sets robot state to STOPPED when there is a objec
*		- Plays sound with the makeSound function
*		- Sets motor speed to MAX_SPEED
*/
// TODO: REMOVE counter and replace with time
int counter = 0;
void moveState() {
	// Get command from app
	string command = "";
	checkBluetoothMessage(command);

	// Startup bot when fire button is pressed on the app
	if (command == "FIRE") {
		STATE = STOPPED;
		return;
	}

	// If we see a object
	if (SensorValue[sensorSonar] < VIEW_DIST) {
		STATE = STOPPED;
		return;
	}

	// Play sound
	counter++;
	if (counter > 75) {
		makeSound();
		counter = 0;
	}


	// TODO: LINE follow

	// Full speed forward
	motor[motorLeft] = MAX_SPEED;
	motor[motorRight] = MAX_SPEED;
}

/**
* @brief Stop state, stops the robot etc
* Move state does the following:
* 	- Uses checkBluetoothMessage function to get command
*   - Sets robot state to MOVING when "FIRE" command is given
*		- uses slowBreak function when motor speed > 0
*/
void stopState() {
	// Get command from app
	string command = "";
	checkBluetoothMessage(command);

	// Startup bot when fire button is pressed on the app
	if (command == "FIRE") {
		STATE = MOVING;
		return;
	}

	// Stop motors if not stopped already
	if (motor[motorLeft] > 0 || motor[motorRight] > 0) {
		slowBreak();
	}
}

/**
* @brief Main, Starts main loop and calls functions based on STATE
*/
task main()
{
	bool running = true;
	while(running) {
		switch(STATE) {
			case MOVING:
				displayBigTextLine(0, "Moving");
				moveState();
				break;
			case STOPPED:
				displayBigTextLine(0, "Stopped");
				stopState();
				break;
			case RIP:
				displayBigTextLine(0, "Rip");
				running = false;
				break;
			default:
				displayBigTextLine(0, "No state");
		}

		wait1Msec(1);
	}
}
